### ISSUE TITLE
add the navbar present in home page of website to all other pages

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Study-Material#2]

**Comment by unnikrishnan2002** [comment]
Can I work on that?

**Comment by arpit456jain** [comment]
just copy paste the code of navbar to all pages

**Comment by unnikrishnan2002** [comment]
Also I do have one more suggestion , it would be great if we could slightly change the color of navbar like this to differentiate between the body and navbar
![IMG-20220120-WA0010](https://user-images.githubusercontent.com/76985777/150366197-17257c81-29fe-4980-a028-aee453df2a1d.jpg)

**Comment by arpit456jain** [comment]
ok

**Comment by unnikrishnan2002** [comment]
So shall I do that also ?

**Comment by arpit456jain** [comment]
Yee

**Comment by code-withAshish** [comment]
it can be solved by just a css property i guess, make it's position fixed so it will stick at the top of the page always
